### ISSUE TITLE
How to use CSS selectors?

### ISSUE THREAD

**Issue by elyezer** [RedHatQE/widgetastic.core#83]
Is it possible to use CSS selectors to locate elements? If not, are you planning to support that?

**Comment by mfalesni** [comment]
1.  Anywhere where locator is expected, by default XPATH locators are expected if passed as a string.
2.  If the string looks like a simple single css locator (`tag#id.class1.class2` with tag being optional and at least one id or class specified), then it processes it as a css locator.
3.  If you want to use a more elaborated CSS locator, you can pass a tuple as you would pass into selenium's `find_elements`
4.  Instead of tuple, you can go more verbose:

```python
from smartloc import Locator  # already a req by wt

SomeWidget(locator=Locator(css='h1 > span'))
```

On the bottom, all locators that widgets' `__locator__` spits out go through https://pypi.python.org/pypi/selenium-smart-locator so whatever works for it should work as a locator. The smart locator is just a namedtuple that works for selenium with some methods added for simplicity.

**Comment by elyezer** [comment]
I think you comment can go into the readme or documentation on a section talking about selecting elements.

There is a line in one of the examples:

```
        another_text = Text('#h2')  # Whatever takes a locator can automatically detect simple CSS locators
```

That can confuse a little because not all widgets accepts locator as the first argument, so I would also recommend updating it to explicitly state `Text(locator='#h2')` because the `TextInput` will try to select `name=<first_argument>` that would translate to `name=#idpassed` and fail to select.

Thank you

**Comment by elyezer** [comment]
Thank you
